# Generated by Django 3.0.4 on 2020-03-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='googlescholarauthors',
        ),
    ]
